version: "3.8"

services:
  app:
    image: aannaassalam/shiftcare-jr:latest
    platform: linux/amd64/v8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "14001:14001"
    restart: always
