name: vps-deploy

on:
  push:
    branches: ["main"]

env:
  REGISTRY: dockerhub.io
  IMAGE_NAME: aannaassalam/shiftcare-jr:latest

jobs:
  publish:
    name: publish docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to docker
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
      - name: Build and Publish in docker hub
        run: |
          docker-compose build
          docker-compose push

  deploy:
    needs: publish
    name: deploy image in remote vps
    runs-on: ubuntu-latest

    steps:
      - name: Login to vps and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_KEY }}
          # password: ${{ secrets.SSH_PASS }}
          port: 22
          script: whoami
